apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # Selector to match the pods targeted by this service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}  # Port on the service
      targetPort: 80  # Port on the pods
  type: {{ .Values.service.type }}  # Exposes the service internally within the cluster
