# Use an official NGINX image as a parent image
FROM nginx:latest

# Copy the website content into the NGINX default directory
COPY index.html .

# Expose port 80 to make the website accessible outside the container
EXPOSE 80
